name: Unit Tests

on:
  push:
    branches: [actions]
  pull_request:
    branches: [master, actions]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm ci
        name: Install modules from npm
      - run: npm run test:all
        name: Run the tests
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build from source